module.exports = {
    before: browser => {
        browser.url('https://devmountain-qa.github.io/enter-wanted/1.4_Assignment/index.html')
    },
    after: browser => {
        browser.end()
    },
    // This test is checking that all Empty Field Messages appear
    'WantedErrorMessages': browser => {
        browser
        .setValue('input[name=hdrInput]','a')
        .click('button[id="saveBtn"]')
        .waitForElementPresent('list[id=errorList]', 3000)
        .useXpath()
        .waitForElementPresent("//li[contains(.,'The \"Header\" field should be between 9 and 19 characters long.')]",3000)
        .waitForElementPresent("//li[contains(.,'The field named \"MKE\" must be included.')]",1000)
        .waitForElementPresent("//li[contains(.,'The field named \"Originating Agency Identifier\" must be included.')]",1000)
        .waitForElementPresent("//li[contains(.,'The field named \"Name\" must be included.')]",1000)
        .waitForElementPresent("//li[contains(.,'The field named \"Sex\" must be included.')]",1000)
        .waitForElementPresent("//li[contains(.,'The field named \"Race\" must be included.')]",1000)
        .waitForElementPresent("//li[contains(.,'The field named \"Height\" must be included.')]",1000)
        .waitForElementPresent("//li[contains(.,'The field named \"Weight\" must be included.')]",1000)
        .waitForElementPresent("//li[contains(.,'The field named \"Hair\" must be included.')]",1000)
        .waitForElementPresent("//li[contains(.,'The field named \"Offense\" must be included.')]",1000)
        .waitForElementPresent("//li[contains(.,'The field named \"Date of Warrant/Violation\" must be included.')]",1000)
        .useCss()
        .click('button[id="clearBtn"]')
        .setValue('input[name=mkeInput]','a')
        .setValue('input[name=oriInput]','a')
        .setValue('input[name=namInput]','aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa')
        .setValue('input[name=sexInput]','a')
        .setValue('input[name=racInput]','aa')
        .setValue('input[name=hgtInput]','a')
        .setValue('input[name=wgtInput]','a')
        .setValue('input[name=haiInput]','a')
        .setValue('input[name=offInput]','a')
        .setValue('input[name=dowInput]','a')
        .setValue('input[name=olnInput]','aaaaaaaaaaaaaaaaaaaaa')
        .setValue('input[name=olsInput]','a')
        .setValue('input[name=olyInput]','a')
        .setValue('input[name=licInput]','a')
        .setValue('input[name=lisInput]','a')
        .setValue('input[name=liyInput]','a')
        .click('button[id="saveBtn"]')
        .useXpath()
        .waitForElementPresent("//li[contains(.,'The field named \"Header\" must be included.')]",3000)
        .waitForElementPresent("//li[contains(.,'The \"MKE\" field should be between 2 and 4 characters long.')]",1000)
        .waitForElementPresent("//li[contains(.,'The \"Originating Agency Identifier\" field should be 9 characters long.')]",1000)
        .waitForElementPresent("//li[contains(.,'The \"Name\" field should be between 1 and 30 characters long.')]",1000)
        .waitForElementPresent("//li[contains(.,'The \"Sex\" field must be entered in as a single character, M for male, F for female, U for unknown.')]",1000)
        .waitForElementPresent("//li[contains(.,'The \"Race\" field should be 1 character long.')]",1000)
        .waitForElementPresent("//li[contains(.,'The \"Height\" field should be 3 characters long.')]",1000)
        .waitForElementPresent("//li[contains(.,'The \"Weight\" field can only include numeric characters.')]",1000)
        .waitForElementPresent("//li[contains(.,'The \"Hair\" field should be between 3 and 10 characters long.')]",1000)
        .waitForElementPresent("//li[contains(.,'The \"Offense\" field should be between 5 and 15 characters long.')]",1000)
        .waitForElementPresent("//li[contains(.,'The \"Date of Warrant/Violation\" field should be 8 characters long.')]",1000)
        .waitForElementPresent("//li[contains(.,'The \"Drivers License\" field should be between 1 and 20 characters long.')]",1000)
        .waitForElementPresent("//li[contains(.,'The \"DL State\" field should be 2 characters long.')]",1000)
        .waitForElementPresent("//li[contains(.,'The \"DL Expiration Date\" field should be 8 characters long.')]",1000)
        .waitForElementPresent("//li[contains(.,'The \"License Plate\" field should be between 5 and 8 characters long.')]",1000)
        .waitForElementPresent("//li[contains(.,'The \"License State\" field should be 2 characters long.')]",1000)
        .waitForElementPresent("//li[contains(.,'The \"License Year\" field should be 4 characters long.')]",1000)
    }
}